__title__ = 'Movens'
__package_name__ = 'movens'
__version__ = '1.0.7'
__description__ = "CLI tool to arrange files smartly"
__email__ = "deepak008@live.com"
__author__ = 'PyContributors'
__github__ = 'https://github.com/Py-Contributors/movens'
__pypi__ = 'https://pypi.org/project/movens'
__license__ = 'MIT License'
